schakelbord = {"a":"a",
               "b":"z",
               "c":"c",
               "d":"d",
               "e":"e",
               "f":"f",
               "g":"g",
               "h":"h",
               "i":"i",
               "j":"j",
               "k":"k",
               "l":"l",
               "m":"m",
               "n":"n",
               "o":"o",
               "p":"p",
               "q":"q",
               "r":"r",
               "s":"s",
               "t":"t",
               "u":"u",
               "v":"v",
               "w": "w",
               "x": "x",
               "y": "y",
               "z": "z"}
for key in schakelbord:
    if input == key:
        heen_enter_rotorI = schakelbord[key]
        print(heen_enter_rotorI)
