rotor_I ={ "a":"e",
           "b":"k",
           "c":"m",
           "d":"f",
           "e":"l",
           "f":"g",
           "g":"d",
           "h":"q",
           "i":"v",
           "j":"z",
           "k":"n",
           "l":"t",
           "m":"o",
           "n":"w",
           "o":"y",
           "p":"h",
           "q":"x",
           "r":"u",
           "s":"s",
           "t":"p",
           "u":"a",
           "v":"i",
           "w":"b",
           "x":"r",
           "y":"c",
           "z":"j"}

rotor_II ={"a":"a",
           "b":"j",
           "c":"d",
           "d":"k",
           "e":"s",
           "f":"i",
           "g":"r",
           "h":"u",
           "i":"x",
           "j":"b",
           "k":"l",
           "l":"h",
           "m":"w",
           "n":"t",
           "o":"m",
           "p":"c",
           "q":"q",
           "r":"g",
           "s":"z",
           "t":"n",
           "u":"p",
           "v":"y",
           "w":"f",
           "x":"v",
           "y":"o",
           "z":"e" }

rotor_III ={"a":"b",
            "b":"d",
            "c":"f",
            "d":"h",
            "e":"j",
            "f":"l",
            "g":"c",
            "h":"p",
            "i":"r",
            "j":"t",
            "k":"x",
            "l":"v",
            "m":"z",
            "n":"n",
            "o":"y",
            "p":"e",
            "q":"i",
            "r":"w",
            "s":"g",
            "t":"a",
            "u":"k",
            "v":"m",
            "w":"u",
            "x":"s",
            "y":"q",
            "z":"o" }
rotor_2 = []
rotor2 = input("Welke rotor op 2e plaats? ")
if rotor2 == "I":
    rotor2 = rotor_I
elif rotor2 == "II":
    rotor2 = rotor_II
elif rotor2 == "III":
    rotor2 = rotor_III
print (rotor2)
